### ISSUE TITLE
Create an example datasets using the data from http://openchargemap.org

### ISSUE THREAD

**Issue by soeren1611** [vocol/mobivoc#7]

**Comment by martindotlindner** [comment]
@clange: Is there any published result/code of the outcome of this project?

**Comment by np00** [comment]
Since we couldn't secure funding, this project never totally hit of. But it is not dead. It touches Logistics, Public Transport & Data Analytics in general. So it overlaps with similar research project from our side. Nevertheless, everything you see here (.ttl files) is the current State of the Art of MobiVoc. 

Indeed, we are planning in the upcoming weeks to do "spring clean up" and will probably focus for now on describing the MDM data: https://service.mdm-portal.de/mdm-portal-application/

Anyone who is interested in MobiVoc is of course welcome to join our initiative.

**Comment by seebi** [comment]
this is now available in https://github.com/vocol/mobivoc/blob/develop/OpenChargeMap_Mobivoc.ttl
